import type { TInteractionInfo } from "./RwaInteractionInfo";

export const korInteractorCriertia: TInteractionInfo[] = [
  {
    title: "자산의 유동성",
    title_eng: "Liquidity",
    description1: `해당 자산이 시장에서 얼마나 쉽게 매매될 수 있는지를 평가합니다. 유동성이 높은 자산은 낮은 유동성 자산보다 투자 리스크가 적습니다. `,
    description2: `평가 요소 : 거래 빈도, 거래량, 시장 참여자 수, 시장의 깊이 등.`,
  },
  {
    title: "법적 안정성 및 규제 준수",
    title_eng: "Evaluation Methodology",
    description1: `해당 자산이 속한 법적 프레임워크 및 규제 환경에 대한 평가입니다. 안정적인 법적 환경과 규제 준수 여부는 투자 안전성에 큰 영향을 미칩니다. `,
    description2: `평가 요소 : 자산이 속한 국가의 법적 안정성, 규제 준수 여부, 국제 규제와의 일관성 등`,
  },
  {
    title: "시장 수요 및 성장 잠재력",
    title_eng: "Market Demand and Growth Potential",
    description1: `자산의 현재 및 미래 시장 수요를 평가합니다. 성장 잠재력이 큰 자산은 장기적인 수익성을 제공합니다.`,
    description2: `평가 요소 : 시장 수요, 시장 성장률, 경쟁 상황, 기술 혁신 및 변화 가능성 등.`,
  },
  {
    title: "자산의 수익성 ",
    title_eng: "Profitability",
    description1: `해당 자산이 생성하는 수익 또는 잠재적 수익성을 평가합니다.`,
    description2: `평가 요소 : 현재 수익률, 과거 성과, 예상 미래 수익, 자산의 비용 구조 등.`,
  },

  {
    title: "자산의 리스크 프로파일 ",
    title_eng: "Risk Profile",
    description1: `자산과 관련된 리스크 요소를 평가합니다. 이는 투자 결정에 중요한 요소로 작용합니다. `,
    description2: `평가 요소 : 신용 리스크, 시장 리스크, 유동성 리스크, 법적 리스크, 운영 리스크 등.`,
  },
];

export const engInteractorCriertia: TInteractionInfo[] = [
  {
    title: "Asset Liquidity",
    description1: `Evaluates how easily the asset can be traded in the market. High liquidity assets have lower investment risks than low liquidity assets.`,
    description2: `Evaluation Factors: Trading frequency, trading volume, number of market participants, market depth, etc.`,
  },
  {
    title: "Legal Stability and Compliance",
    description1: `Evaluates the legal framework and regulatory environment in which the asset operates. A stable legal environment and regulatory compliance significantly impact investment safety.`,
    description2: `Evaluation Factors: Legal stability in the asset's country, regulatory compliance, consistency with international regulations, etc.`,
  },
  {
    title: "Market Demand and Growth Potential",
    description1: `Evaluates the current and future market demand for the asset. Assets with high growth potential offer long-term profitability.`,
    description2: `Evaluation Factors: Market demand, market growth rate, competitive landscape, potential for technological innovation and change, etc.`,
  },
  {
    title: "Profitability",
    description1: `Evaluates the profit or potential profitability generated by the asset.`,
    description2: `Evaluation Factors: Current yield, past performance, expected future returns, asset cost structure, etc.`,
  },
  {
    title: "Risk Profile",
    description1: `Evaluates the risk factors associated with the asset. This is a crucial factor in making investment decisions.`,
    description2: `Evaluation Factors: Credit risk, market risk, liquidity risk, legal risk, operational risk, etc.`,
  },
];

export const korInteractoMethodology: TInteractionInfo[] = [
  {
    title: "정량적 분석",
    title_eng: "Quantitative Analysist",
    description1: `수치화된 데이터를 기반으로 자산의 가치를 평가하는 방법입니다.`,
    description2: `방법론: 자산의 재무제표 분석, 수익률 계산, 변동성 분석, 시뮬레이션 모델링 등을 통해 객관적 지표를 도출합니다. `,
    description3: `도구 : 재무 비율 분석(ROI, ROE 등), VaR(Value at Risk), 몬테카를로 시뮬레이션 등.`,
  },
  {
    title: "정성적 분석",
    title_eng: "Qualitative Analysis",
    description1: `자산과 관련된 비재무적 요소들을 평가하는 방법입니다.`,
    description2: `방법론: 산업 분석, 경영진의 역량 평가, 법적 리스크 평가, 시장 트렌드 분석 등을 포함합니다.`,
    description3: `도구 : SWOT 분석, 포터의 5가지 힘 분석, PESTEL 분석 등.`,
  },
  {
    title: "등급 평가 모델",
    title_eng: "Rating Model",
    description1: `위의 정량적, 정성적 분석 결과를 바탕으로 자산에 등급을 매기는 방법입니다. `,
    description2: `방법론 : 각각의 평가 요소에 가중치를 부여하여 종합 점수를 산출한 후, 해당 점수에 따라 자산을 CCC부터 AAA까지의 등급으로 분류합니다. `,
    description3: `도구 : 등급 평가 알고리즘, 통계적 분석 모델, 머신러닝 기반 예측 모델 등.`,
  },
  {
    title: "시나리오 분석",
    title_eng: "Scenario Analysis",
    description1: `다양한 시장 상황을 가정하여 자산의 성과를 예측하는 방법입니다.`,
    description2: `방법론 : 경기 침체, 금리 인상, 규제 변화 등 다양한 시나리오를 설정하고, 각 시나리오에서 자산의 가치 변화를 평가합니다.`,
    description3: `도구 : 시나리오 플래닝 툴, 스트레스 테스트, 민감도 분석 등.`,
  },
];

export const engInteractoMethodology: TInteractionInfo[] = [
  {
    title: "Quantitative Analysist",
    description1: `A method of evaluating the value of an asset based on quantified data.`,
    description2: `Methodology: Financial statement analysis, yield calculations, volatility analysis, simulation modeling, etc., to derive objective indicators.`,
    description3: `Tools: Financial ratio analysis (ROI, ROE, etc.), VaR (Value at Risk), Monte Carlo simulation, etc.`,
  },
  {
    title: "Qualitative Analysis",
    description1: `A method of evaluating non-financial factors related to the asset.`,
    description2: `Methodology: Industry analysis, management capability evaluation, legal risk assessment, market trend analysis, etc.`,
    description3: `Tools: SWOT analysis, Porter's Five Forces analysis, PESTEL analysis, etc.`,
  },
  {
    title: "Rating Model",
    description1: `A method of rating assets based on the results of quantitative and qualitative analysis.`,
    description2: `Methodology: Assign weights to each evaluation factor, calculate a composite score, and classify the asset's rating from CCC to AAA based on that score.`,
    description3: `Tools: Rating evaluation algorithms, statistical analysis models, machine learning-based predictive models, etc.`,
  },
  {
    title: "Scenario Analysis",
    description1: `A method of predicting the asset's performance under various market conditions.`,
    description2: `Methodology: Set various scenarios such as economic downturn, interest rate hikes, regulatory changes, and evaluate asset value changes under each scenario.`,
    description3: `Tools: Scenario planning tools, stress tests, sensitivity analysis, etc.`,
  },
];

export const korInteractoProvision: TInteractionInfo[] = [
  {
    title: "요약 리포트 제공",
    title_eng: "Summary Report",
    description1: `각 RWA 프로젝트에 대한 주요 평가 결과와 등급을 간단히 요약한 보고서를 제공합니다.`,
    description2: ``,
  },
  {
    title: "상세 리포트",
    title_eng: "Detailed Report",
    description1: `평가에 사용된 모든 데이터와 분석 방법을 상세히 기술하여, 투자자들이 평가 과정과 결과를 투명하게 이해할 수 있도록 합니다.`,
    description2: ``,
  },
  {
    title: "리스크 및 기회 평가",
    title_eng: "Risk and Opportunity Assessment",
    description1: `자산의 주요 리스크와 기회를 구체적으로 분석하여, 투자자들이 정보에 입각한 결정을 내릴 수 있도록 지원합니다.`,
    description2: ``,
  },
];

export const engInteractoProvision: TInteractionInfo[] = [
  {
    title: "Summary Report",
    description1: `Provides a brief summary of the main evaluation results and ratings for each RWA project.`,
    description2: `Evaluation Factors: Trading frequency, trading volume, number of market participants, market depth, etc.`,
  },
  {
    title: "Detailed Report",
    description1: `Describes in detail all data and analysis methods used in the evaluation, allowing investors to transparently understand the evaluation process and results.`,
    description2: `Evaluation Factors: Trading frequency, trading volume, number of market participants, market depth, etc.`,
  },
  {
    title: "Risk and Opportunity Assessment",
    description1: `Specifically analyzes the major risks and opportunities of the asset, helping investors make informed decisions.`,
    description2: `Evaluation Factors: Trading frequency, trading volume, number of market participants, market depth, etc.`,
  },
];
